### ISSUE TITLE
mfnm console and console_clean trigger termination (application_start_failure)

### ISSUE THREAD

**Issue by tadr** [rzezeski/try-try-try#3]
Installed r14b03. Attempted two version of rebar:

rebar version: 2 date: 20110823_173019 vcs: git 1dcf0d1
rebar version: 2 date: 20110929_215853 vcs: git 0279cb2

I followed your instructions up to 'make rel', then tried mfnm console:

jammer:mfmn tadr$ ./rel/mfmn/bin/mfmn console
Exec: /Users/tadr/code/riak-examples/mfmn/rel/mfmn/erts-5.8.4/bin/erlexec -boot /Users/tadr/code/riak-examples/mfmn/rel/mfmn/releases/1/mfmn -embedded -config /Users/tadr/code/riak-examples/mfmn/rel/mfmn/etc/app.config -args_file /Users/tadr/code/riak-examples/mfmn/rel/mfmn/etc/vm.args -- console
Root: /Users/tadr/code/riak-examples/mfmn/rel/mfmn
{error_logger,{{2011,11,3},{22,34,5}},"Protocol: ~p: register error: ~p~n",["inet_tcp",{{badmatch,{error,duplicate_name}},[{inet_tcp_dist,listen,1},{net_kernel,start_protos,4},{net_kernel,start_protos,3},{net_kernel,init_node,2},{net_kernel,init,1},{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}]}
{error_logger,{{2011,11,3},{22,34,5}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.20.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.256>,<0.17.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,377},{stack_size,24},{reductions,445}],[]]}
{error_logger,{{2011,11,3},{22,34,5}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfargs,{net_kernel,start_link,[['mfmn@127.0.0.1',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2011,11,3},{22,34,5}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2011,11,3},{22,34,5}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})

---

erl_crash.dump is here:

http://spacekitty.net/files/erl_crash.dump

**Comment by rzezeski** [comment]
It looks like you might already have a node named `mfmn@127.0.0.1` running.

What is the output of `ps aux | grep beam`?  Might want to try killing all beam processes as well as `epmd`.

**Comment by tadr** [comment]
I was sure that I wasn't running other mfnm processes. I checked with epmd -names. I must have goofed somehow, because I'm able to reproduce this problem when a mfnm process is started. And, it seems to be working otherwise.

This is one of my first forays into anything-Erlang, so thanks for working with my ignorance.

Tad

**Comment by rzezeski** [comment]
It's cool.  It's happened to me before too.  Good to hear it's working now.

**Comment by tadr** [comment]
Hey, I forgot to mention that I really appreciate your posts. They are quite good. Thanks.
